# Плагин принадлежит студии KleksyStudio - vk.com/kleksystudio
# Данный плагин защищён апвторским правом!
# Любые изменения, доработки категорически запрещены без разрешения автора плагина - KleksyStudio
#
# Настройки прав и наличии "библиотек-плагинов" отсутствует.
messages:
  # Сообщения кика игрока по причине неизвестного IP-адреса
  nullAddress: '&cВы были кикнуты!\n&cВаш айпи адрес не распознан!'
  # Сообщения кика игрока по причине подменой UUID шифроманием игрока
  sproofUUID: '&cВы были кикнуты!\n&cПопытка подмены UUID!'
  # Сообщения кика игрока по причине неизвестного UUID шифрованием игрока
  nullUUID: '&cВы были кикнуты!\n&cНеизвестный UUID!'
  # Сообщения кика игрока по причине недоступностью серверов Mojang
  mojangDown: '&cВы были кикнуты!\n&cСервера Mojang не работают!'
settings:
  # Скрыть сообщение при заходе игрока
  join: true
  # Скрыть сообщение при выходе игрока
  quit: true
  # Скрыть сообщение при смерти игрока
  death: true
  # Отключить сгорание блока
  burn: true
  # Отключить вырастание блоков
  grow: true
  # Отклюить горение блока
  ignite: true
  # Отключить взрывы
  explosions: true
  # Отключить взаимодействие с блоками
  blocks: true
  # Использование чата
  chat: true
  # Скрыть показ ачивок
  advancements: true
  # Отключить использование команд
  commands: true
  # Команды доступные для использования
  commandsWhitelist:
    - 'menu'
    - 'donate'
    - 'spawn'
  # Отключить любой урон
  damage: true
  # Отключить любое истощение
  feed: true
  # Отключить любое изменение здоровья
  heal:
    # Отключить
    enable: true
    # Установить здоровье в значение
    health: 0.5
  # Исправление ошибок
  fix:
    # Включить исправление ошибки связанной с киком игрока за частое нажатие на TAB при выборе команды
    antiDisconnectSpam: true
    # Включить исправление ошибки связанной с неизвестным IP-адресом
    nullAddress: true
    # Включить исправление ошибки связанной с подменой UUID шифроманием игрока
    sproofUUID: true
    # Включить исправление ошибки связанной с неизвестным чанком
    nullChunk: true
    # Включить исправление ошибки связанной с неизвестным UUID шифрованием игрока
    nullUUID: true
    # Включить исправление ошибки связанной с недоступностью серверов Mojang
    mojangDown: true